# Generated by Django 3.2.25 on 2025-01-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='0d726764-745a-4880-a153-1949dd9dd609', max_length=500, null=True),
        ),
    ]
