# Generated by Django 3.2.25 on 2025-01-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='4b709665-f3bd-49d9-91c2-ae4c22d6bc46', max_length=500, null=True),
        ),
    ]
